### DISCUSSION TITLE
Test Coverage

### DISCUSSION THREAD

**Discussion by giobart** [oakestra/oakestra#161] [General]
It is possible to setup a coverage tool like Codecov. For our public repos it is free and compatible with GitHub Workflows

## Codecov example

we can setup a worflow for each component as follows 

```
name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      working-directory: root_orchestrator/system-manager-python
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      working-directory: root_orchestrator/system-manager-python
      run: pytest --cov .
```

This example runs pytest coverage on our system manager for each push and pull request.

## PR rules 

It is possible to block a PR if the test coverage decreases with respect to the previous commit. 
Example:

```
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 50%
        paths: 
          - "root_orchestrator/system-manager-python"
```

this example sets a minimum coverage threshold o 50% and blocks the pull requests that decrease the coverage with respect to previous commit. 
Ideally we should periodically increase the threshold up to 90%

# Discussion

Do you know better ways of doing this? Pros and cons? 

I'm looking forward to read your comments either here or in our next meeting!
