### ISSUE TITLE
Missing Resource abstractor from 1-DOC

### ISSUE THREAD

**Issue by giobart** [oakestra/oakestra#268]
## Short
The new resource abstractor service is missing from 1-DOC

## Solution 
Need to add the entires like 
```
resource_abstractor:
    image: resource_abstractor
    build: resource-abstractor/
    container_name: resource_abstractor
    hostname: resource_abstractor
    expose:
      - "11011"
    ports:
      - "11011:11011"
    environment:
      - RESOURCE_ABSTRACTOR_PORT=11011
      - CLOUD_MONGO_URL=mongo
      - CLOUD_MONGO_PORT=10007
    depends_on:
      - mongo_root
```

to 1-DOC

## Status
Implementing

## Checklist
- [ ] Discussed
- [ ] Solved
- [ ] Tested
