### ISSUE TITLE
Allow larger service names

### ISSUE THREAD

**Issue by giobart** [oakestra/oakestra#307]
## Short
Allow SLA containing larger service names

## Proposal 
refer to:  https://github.com/oakestra/oakestra-net/issues/168

## Solution 
Root orch validation and removal of max 8 char long service name limitation

## Status
development

## Checklist
- [x] Discussed
- [ ] Solved
- [ ] Tested

**Comment by Malyuk-A** [comment]
I think that the latest change is sadly not enough to resolve this issue. It allows the creation of longer-named apps and services but not their deployment.

Examples

Here is an SLA where the app names are just under 30 chars and the service name has the legacy length of max 8 chars

```yaml
{
    "sla_version": "v2.0",
    "customerID": "Admin",
    "applications": [
        {
            "applicationID": "",
            "application_name": "validappenamethatisalright",
            "application_namespace": "validappnamespacethatisoki",
            "application_desc": "Simple demo with curl client and Nginx server",
            "microservices": [
                {
                    "microserviceID": "",
                    "microservice_name": "tinyname",
                    "microservice_namespace": "minins",
                    "virtualization": "container",
                    "cmd": [
                        "sh",
                        "-c",
                        "tail -f /dev/null"
                    ],
                    "memory": 100,
                    "vcpus": 1,
                    "vgpus": 0,
                    "vtpus": 0,
                    "bandwidth_in": 0,
                    "bandwidth_out": 0,
                    "storage": 0,
                    "code": "docker.io/curlimages/curl:7.82.0",
                    "state": "",
                    "port": "9080",
                    "added_files": []
                }
            ]
        }
    ]
}
```
![image](https://github.com/oakestra/oakestra/assets/65814168/a1ea32bb-b0bb-444c-a699-ff56708e378c)
![image](https://github.com/oakestra/oakestra/assets/65814168/f7a6225c-0088-4e45-a112-734fb9d462ae)

![image](https://github.com/oakestra/oakestra/assets/65814168/e201f7a8-f1d5-40dd-bf97-cedf587e71ab)


Here is another SLA where also the service names are larger than 8 chars but smaller than 30 chars

```yaml
{
    "sla_version": "v2.0",
    "customerID": "Admin",
    "applications": [
        {
            "applicationID": "",
            "application_name": "validappenamethatisalright",
            "application_namespace": "validappnamespacethatisoki",
            "application_desc": "Simple demo with curl client and Nginx server",
            "microservices": [
                {
                    "microserviceID": "",
                    "microservice_name": "validservicenamethatisalright",
                    "microservice_namespace": "validservicenamespacethatisok",
                    "virtualization": "container",
                    "cmd": [
                        "sh",
                        "-c",
                        "tail -f /dev/null"
                    ],
                    "memory": 100,
                    "vcpus": 1,
                    "vgpus": 0,
                    "vtpus": 0,
                    "bandwidth_in": 0,
                    "bandwidth_out": 0,
                    "storage": 0,
                    "code": "docker.io/curlimages/curl:7.82.0",
                    "state": "",
                    "port": "9080",
                    "added_files": []
                }
            ]
        }
    ]
}

```
![image](https://github.com/oakestra/oakestra/assets/65814168/13b00c3f-3ff3-4f6a-8ace-611626d3bbfb)

---

So it is possible to create apps and services with names and namespaces that are <30 chars but not deploy them because the underlying components concatenate all of them together and if their sum is longer than 76 chars they can no longer be deployed.
